services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DJANGO_ENVIRONMENT: production
      DJANGO_DEBUG: "False"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
    volumes: []
    restart: unless-stopped

  celery-worker:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DJANGO_ENVIRONMENT: production
      DJANGO_DEBUG: "False"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes: []
    restart: unless-stopped

  celery-beat:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.production
      DJANGO_ENVIRONMENT: production
      DJANGO_DEBUG: "False"
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes: []
    restart: unless-stopped

  db:
    restart: unless-stopped

  redis:
    restart: unless-stopped
